/**:
  ros__parameters:
    robot_name: ""
    distance_from_wall: 0.7
    distance_to_stop: 0.65
    max_linear_vel: 0.15
    max_angular_vel: 0.7
    min_angular_vel: -0.7
    sampling_rate: 0.033
    kp: 12.0
    ki: 0.0
    kd: -0.2
    kp2: 0.1
    ki2: 0.0
    kd2: 0.0
    start_deg_lateral: 69
    end_deg_lateral: 78
    ray_th: 16
    wheel_separation: 0.28
    distance_to_turn: 1.0
    distance_to_skip: 1.0
    gap_deg: 65
