/**:
  ros__parameters:
    cmd_vel_topic_name: "raspicat_cmd_vel"
    distance_from_wall: 0.8
    distance_to_stop: 0.9
    max_linear_vel: 0.22
    max_angular_vel: 0.7
    min_angular_vel: -0.7
    sampling_rate: 0.033
    kp: 12.0
    ki: 0.0
    kd: 0.0
    start_deg_lateral: 69
    end_deg_lateral: 78
    stop_ray_th: 0.3
    wheel_separation: 0.28
    distance_to_skip: 1.0
    open_place_distance: 12.5
    detection_div_deg: [-15., 15., 15., 45., -45., -15.]
    select_angvel: [0., 0.35, -0.35]
