/**:
  ros__parameters:
    robot_name: "turtlebot3"
    distance_from_wall: 0.8
    distance_to_stop: 0.85
    max_linear_vel: 0.25
    max_angular_vel: 0.5
    min_angular_vel: -0.5
    sampling_rate: 0.033
    kp: 12.0
    ki: 0.0
    kd: -0.1
    start_deg_lateral: 69
    end_deg_lateral: 78
    ray_th: 16
    wheel_separation: 0.28
