/**:
  ros__parameters:
    robot_name: "turtlebot3"
    distance_from_wall: 0.4
    distance_to_stop: 0.45
    max_linear_vel: 0.22
    max_angular_vel: 2.84
    min_angular_vel: -2.84
    sampling_rate: 0.033
    kp: 4.5
    ki: 0.005
    kd: 0.25